#!/usr/bin/env bash
# Display information about subdomains

display_info () {
    domain="$1"
    subdomain="$2"

    # Retrieve the information from dig command using awk
    dig_output=$(dig +short "$subdomain.$domain")

    # Check if the dig command returned any output
    if [ -n "$dig_output" ]; then
        record_type=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $4}')
        destination=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{getline; print $5}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

# Check for subdomains: www, lb-01, web-01, web-02
for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ]; then
        display_info "$1" "$subdomain"
    fi
done
