#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello world!" when queried
#++    at the root with a curl GET request.

 apt-get -y update
 apt-get -y install nginx
 'Hello World!' > /var/www/html/index.nginx-debian.html
 service nginx start