#!/usr/bin/env bash
#Creating a script that lists files
for i in *
do
    echo "$i" | cut -f 2- -d '-'
done#!/usr/bin/env bash
#Creating a script that lists files
for i in *
do
    echo "$i" | cut -f 2- -d '-'
done
