#!/usr/bin/env bash
# Configures the ufw firewall to block all  the incoming traffic
# except for the TCP ports 22, 443 and 80.

sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable

