#!/bin/bash

# Task 1: Configure web-01 firewall to forward port 8080/TCP to port 80/TCP using iptables
sudo iptables -A PREROUTING -t nat -p tcp --dport 8080 -j REDIRECT --to-port 80

# Save iptables rules so they persist after reboot
sudo iptables-save > /etc/iptables/rules.v4
